### PR TITLE
Update version and readme

### PR DESCRIPTION
**Pull request by M5oul**
- update to version 1.1.7 which fix security issues.
- readme: remove website which no more exist. Other typos.

### CODE REVIEW

**Comment by M5oul** [comment]
@JimboJoe, manifest updated.
@polytan02,  I will let someone else change version variable convention.

**Comment by frju365** [comment]
I can do this if you want.

**Comment by frju365** [comment]
location of the version ? you mean the version number in the url ?

**Comment by polytan02** [comment]
Your second commit is fine but try not to mix to many things in in go :)

**Comment by M5oul** [comment]
Rebased on #22 as there will be conflicts.

**Pull request closed without merging**
